USE TayqaMobileApp

Declare @firm int = 9;
Declare	@firmNr nvarchar(10)= '9';
Declare @activePeriod nvarchar (10)= '5';

INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (4,'SyncSalesMan', 'SalesMan', 'Sync SalesMan', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncSalesMan', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (5,'RefreshSalesMan', 'SalesMan', 'Refresh SalesMan', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshSalesMan', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (6,'RefreshDivision', 'Division', 'Refresh Division', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshDivision', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (7,'RefreshWareHouse', 'Warehouse', 'Refresh Warehouse', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshWarehouse', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (8,'SyncExpenseCenter', 'ExpenseCenter', 'Sync Expense Center', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncExpenseCenter', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (9,'RefreshExpenseCenter', 'ExpenseCenter', 'Refresh Expense Center', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshExpenseCenter', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (10,'RefreshFactory', 'Factory', 'Refresh Factory', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshFactory', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (11,'RefreshCurrency', 'Currency', 'Refresh Currency', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshCurrency', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (12,'SyncProject', 'Project', 'Sync Project', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncProject', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (13,'RefreshProject', 'Project', 'Refresh Project', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshProject', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (14,'SyncCashCard', 'CashCard', 'Sync Cash Card', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncCashCard', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (15,'RefreshCashCard', 'CashCard', 'Refresh Cash Card', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshCashCard', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (16,'SyncClient', 'Client', 'Sync Client', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncClient', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (17,'RefreshClient', 'Client', 'Refresh Client', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshClient', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (18,'SyncItemAll', 'Item', 'Sync Item', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncItemAll', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (19,'RefreshItemAll', 'Item', 'Refresh Item', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshItemAll', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (20,'RefreshPermittedClient', 'PermittedClient', 'Refresh Permitted Client', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshPermittedClient', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (21,'RefreshItemStock', 'ItemStock', 'Refresh Item Stock', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshItemStock', 2, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (22,'RefreshClientDebt', 'ClientDebt', 'Refresh Client Debt', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshClientDebt', 2, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (23,'RefreshDepartment', 'Department', 'Refresh Department', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshDepartment', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (24,'RefreshTradingGroup', 'TradingGroup', 'Refresh Trading Group', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshTradingGroup', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (25,'RefreshAuthToken', 'AuthToken', 'Refhresh Auth Token', 'GET', 'http://10.91.10.24:1150/tayqa/tiger/api/core/v2.9.1/uid/RefreshAuthToken', 5, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (26,'SyncPaymentPlan', 'PaymentPlan', 'Sync Payment Plan', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncPaymentPlan', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (27,'RefreshPaymentPlan', 'PaymentPlan', 'Refresh Payment Plan', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshPaymentPlan', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (28,'RefreshClientFinance', 'ClientFinanceData', 'Refresh Client Finance Data', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshClientFinance', 2, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (31,'RefreshClientRoute', 'ClientRoute', 'Refresh Client Route', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshClientRoute', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (32,'SyncBank', 'Bank', 'Sync Bank', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncBank', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (33,'RefreshBank', 'Bank', 'Refresh Bank', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshBank', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (34,'SyncBankAccount', 'BankAccount', 'Sync Bank Account', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/SyncBankAccount', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (35,'RefreshBankAccount', 'BankAccount', 'Refresh Bank Account', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshBankAccount', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (42,'RefreshClientGroupDataForItemCatalog', 'ClientGroupdDataForCatalog', 'Refresh Client Group data for Item catalog', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshClientGroupDataForItemCatalog', 1, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (51,'RefreshOprFactDistributedByClient', 'OprFactDistributedByClient', 'Refresh Opr Fact Distributed Client', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshOprFactDistributedByClient', 2, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (52,'RefreshOprFactDistributedByUser', 'OprFactDistributedByUser', 'Refresh Opr Fact Distributed User', 'POST', 'http://10.91.10.24:1401/core/v2.91/TigerCore/RefreshOprFactDistributedByUser', 2, 1, NULL, NULL, 1, GETDATE())
INSERT [dbo].[SYS_DataExchangeMethod] ([Id], [Name], [Source], [Description], [ExtraInfo], [Url], [DataTypeId], [Status], [ModifiedUserId], [ModifiedDate], [CreatedUserId], [CreatedDate]) VALUES (100,'ReconnectToLogo', 'ReconnectToLogo', 'Integration Reconnect To Logo', 'POST', 'http://10.91.10.24:11101/core/Integration/ReconnectToLogo', 3, 1, NULL, NULL, 1, GETDATE())


--INSERT INTO OP_DataExchangeStatus

INSERT INTO OP_DataExchangeStatus (LastSyncAt,MethodId,Note,RegisteredAt,RegisteredUserId,Status,ResponseStatus,Firm)
		SELECT GETDATE(),M.Id,'',GETDATE(),606,1,'',9
		FROM SYS_DataExchangeMethod M

--INSERT INTO OP_DataExchangeSchedule

INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (1, 4, '{"Firms": ['+ @firmNr +']}', NULL, 1800, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (5, 6, '{"Firms": ['+ @firmNr +']}', NULL, 1800, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (6, 7, '{"Firms": ['+ @firmNr +']}', NULL, 1800, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (7, 8, '{"Firms": ['+ @firmNr +']}', NULL, 1800, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (8, 9, '{"Firms": ['+ @firmNr +']}', NULL, 86400,1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (9, 10, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (10, 11, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (11, 12, '{"Firms": ['+ @firmNr +']}', NULL, 1800, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (12, 13, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (13, 14, '{"Firms": ['+ @firmNr +']}', NULL, 1800, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (14, 15, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (15, 16, '{"Firms": ['+ @firmNr +']}', NULL, 1800, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (16, 17, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (17, 18, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (18, 19, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (19, 20, '{"Firms": ['+ @firmNr +']}', NULL, 1800, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (20, 23, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (21, 21, '{"Firms":[{"Nr":'+ @firmNr +', "ActivePeriod":'+ @activePeriod +'}]}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (22, 22, '{"Firms":[{"Nr":'+ @firmNr +', "ActivePeriod":'+ @activePeriod +'}]}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (25, 5, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (27, 24, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (28, 25, '','AuthToken', 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (31, 31, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (33, 32, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (34, 33, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (35, 34, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
INSERT [dbo].[OP_DataExchangeSchedule] ([Id], [DataExchangeMethodId], [Parameters], [ExtraInfo], [Period], [Status], [Note], [NextSyncTime], [LastExecutionTime], [ExtraNote]) VALUES (36, 35, '{"Firms": ['+ @firmNr +']}', NULL, 86400, 1, '' ,  GETDATE(), '', '')
