truncate table SYS_ExcelTemplate

GO

INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Mal mehdudiyyetleri', N'Mal seviyyesinde mehdudiyyet', N'C:\TayqaSale\ExcelTemplates\Mal mehdudiyyeti_9543493EEAF541BF8095707338AF97A5.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Mal mehdudiyyetleri', N'Musteri seviyyesinde mal mehdudiyyeti', N'C:\TayqaSale\ExcelTemplates\Musteriye gore mal mehdudiyyeti_26A161E646D949BC97D4202F680625F8.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Mal mehdudiyyetleri', N'Musteri qrup seviyyesinde mal mehdudiyyeti', N'C:\TayqaSale\ExcelTemplates\Musteri qrupuna gore mal mehdudiyyeti_3B7C67AE1312425781748C2FAA291EC2.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Kataloqa toplu şəkildə məhsulların elave olunmasi', N'Kataloqa toplu sekilde mehsullarin elave edilmesi', N'C:\TayqaSale\ExcelTemplates\Kataloqa toplu şəkildə məhsulların elave olunmasi_D759A61B28E541B3B156E68C9137C0C1.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musterileri qadagan etmek sablonu', N'C:\TayqaSale\ExcelTemplates\Musterileri qadagan etmek sablonu_221DAC7FA84A4E5ABF6C94E4542FF0A8.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Istifadecilere toplu kataloq yetkilerinin verilmesi', N'İstifadəçilərə toplu kataloq səlahiyyətinin verilməsi şablonu', N'C:\TayqaSale\ExcelTemplates\İstifadəçilərə toplu kataloq səlahiyyətinin verilməsi şablonu_BF180A724D744DD9956C96C2A1001832.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Istifadecilere lokal musteri selahiyyetinin verilmesi', N'C:\TayqaSale\ExcelTemplates\Musteri lokal Selahiyyet_3ADDB22D59294C1DA5EF0329ED5AF0AF.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Qiymet Idareetmesi', N'Musteri ve ya musteri qrupuna gore ozel qiymetlendirme', N'C:\TayqaSale\ExcelTemplates\MusteriVSMusteri qrupuna ozel qiymetlendirme_B7931E91D03240C59C8194B0584D5DFB.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Qiymet Idareetmesi', N'Mehsul qiymetinin deyisdirilmesi (esas,musteri,musteri qrupu)', N'C:\TayqaSale\ExcelTemplates\Qiymet deyisdirmek_D0574A839CE94EFBBB248263052CEDF2.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Istifadeciye satis numayenderinin baglanmasi', N'Istifadeciye satis numayenderinin baglanmasi', N'C:\TayqaSale\ExcelTemplates\Istifadeciye satis numayenderinin baglanmasi_1920F45E51D9413186410EC74B065EEE.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musterilere xususi mehsul mehdudiyyetleri', N'C:\TayqaSale\ExcelTemplates\Xüsusi məhsul məhdudiyyətləri şablonu_68D71334F120434ABE4EB094070957D1.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES ( N'Musteriler', N'Musterilerin daxil edilmesi (CRM)', N'C:\TayqaSale\ExcelTemplates\Musterilerin daxil edilmesi (CRM)_39ACCF65E7EF4012925D47E676470FF1.xlsx', 9);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Ankete musterilerin elave edilmesi', N'C:\TayqaSale\ExcelTemplates\Ankete musterilerin elave edilmesi_4649E762DBA24746896D4078600CAC7E.xlsx', 4);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Suallar', N'He , Yox tipli suallarin elave edilmesi', N'C:\TayqaSale\ExcelTemplates\Suallarin elave edilmesi_4BB59451C4B04A84B09065EAFC750661.xlsx', 4);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Rut VS Gps mehdudiyyetleri', N'Istifadecilerin Rut ve Gps mehdudiyyetlerinin aktiv ve ya passiv olunmasi', N'C:\TayqaSale\ExcelTemplates\Rut VS Gps mehdudiyyetleri_AB21342D7D154F2D975D70EFC9821956.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musterilerin ruta elave olunmasi (Heftenin gunleri)', N'C:\TayqaSale\ExcelTemplates\Rutlarin importu (Heftenin gunleri)_2864D588B00D472AA6F458CE721A1753.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musteriler ruta elave olunmasi (Tarix)', N'C:\TayqaSale\ExcelTemplates\Rutlarin importu (Tarix)_1AEB103D3A9A4679BDBB2C38E9FFF5BC.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musterilerin qruplara elave edilmesi', N'C:\TayqaSale\ExcelTemplates\Musterilerin qruplara elave edilmesi_3E1004DE9B4C4ED189D50C14CA3BB879.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Qiymet idareetmesi', N'Mehsullarin esas, musteri , musteri qruplari seviyyesinde  qiymet deyisiklikleri', N'C:\TayqaSale\ExcelTemplates\Qiymet deyisiklikleri_6F0932F2252B4412B39D9E545FCCC92A.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musterilerde Gps mehdudiyyetinin legv edilmesi', N'C:\TayqaSale\ExcelTemplates\Musterilerde Gps mehdudiyyetinin legv edilmesi_A279D98304BC4CE1925577D935033285.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Temsilciler', N'Temsilcilere musteri baglantilarinin verilmesi', N'C:\TayqaSale\ExcelTemplates\Musteri temsilci baglantisi_B93FA52BCC6A490C96EDAFBC9C1F89BD.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES ( N'Temsilciler', N'Temsilcilerin yaradilmasi', N'C:\TayqaSale\ExcelTemplates\Temsilcilerin yaradilmasi_4B5C62E3E99F438FB92E927E84B3140E.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Inventarlar', N'Inventarlarin sisteme daxil olunmasi', N'C:\TayqaSale\ExcelTemplates\İnventar import sablonu_213BD3AE95294446A42ED385065BC5B9.xlsx', 1);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Kompleks KPI', N'Musteri elaqesi strukturu', N'C:\TayqaSale\ExcelTemplates\Musteri elaqesi strukturu_A296CA5DCBAE4AC09268DB15B8C152E5.xlsx', 4);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Mal parametrleri', N'Mal parametrlerinin elave edilmesi', N'C:\TayqaSale\ExcelTemplates\Mal parametrlerinin elave edilmesi_AF7366CA7C6F4C539897CF8591B08563.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musteri ve musteri qrupuna gore mebleq mehdudiyyetleri', N'C:\TayqaSale\ExcelTemplates\Emeliyyat uzre mebleq mehdudiyyetleri_7BCEF35FB2C6452AB55C394C99975C77.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES ( N'Plan-Fakt', N'Mehsullarin qruplara elave edilmesi', N'C:\TayqaSale\ExcelTemplates\Mehsullarin qruplara elave edilmesi_E684F91457804217903441B31D70066F.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Rut sablonu idareetmesi', N'C:\TayqaSale\ExcelTemplates\Rut şablonu importu_6D4E7209E2B34BDB972FDEB04991D2B5.xlsx', 9);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Inventarlar', N'Is yeri, anbar, veziyyet, mesul sexslerin toplu redakte olunmasi', N'C:\TayqaSale\ExcelTemplates\Inventarlarin toplu sekilde redakte olunmasi_8392582E954948D3B7B9C277AEE55701.xlsx', 1);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Inventarlar', N'Avadanliq mehsul elaqesi', N'C:\TayqaSale\ExcelTemplates\Avadanliq mehsul elaqesi_FBF713C45C2543FABBE713B2FCEC369C.xlsx', 1);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Xususi kod mezmun elaqeleri', N'Xususi kod mezmun elaqeleri', N'C:\TayqaSale\ExcelTemplates\Xususi kod mezmun elaqeleri_7ACE4B98B9364EC48F201593E938A425.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Mal mehdudiyyetleri', N'Mal qaytarma anbar mehdudiyyetleri', N'C:\TayqaSale\ExcelTemplates\Mal qaytarma anbar mehdudiyyeti_B5BA52E2AA9044B087C3ECC7F2C1E5AE.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Istifadecilere lokal musteri selahiyyetinin verilmesi 3.2', N'C:\TayqaSale\ExcelTemplates\Musteri lokal Selahiyyet 3.2_F1855614B00640819E2C42D3BD04E366.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musteriler ruta elave olunmasi (Tarix) 3.2', N'C:\TayqaSale\ExcelTemplates\Musteriler ruta elave olunmasi (Tarix) 3.2_742E17384286410FAD429BA005234331.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musterilerin ruta elave olunmasi (Heftenin gunleri) 3.2', N'C:\TayqaSale\ExcelTemplates\Musterilerin ruta elave olunmasi (Heftenin gunleri) 3.2_FA8F9D5F1D5F43B3AD871204C5FEB1F9.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Kataloqa toplu sekilde mehsullarin redakte edilmesi', N'Kataloqa toplu sekilde mehsullarin redakte edilmesi', N'C:\TayqaSale\ExcelTemplates\Kataloqa toplu sekilde mehsullarin redakte edilmesi_872FF6BB47174567822BACDE302C451B.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Musteriler', N'Musteri qruplarina xususi mehsul mehdudiyyetleri', N'C:\TayqaSale\ExcelTemplates\Xüsusi məhsul məhdudiyyətləri şablonu_0450EA1C6F2F48B1B312E7F1C39803D6.xlsx', 3);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Xususi kod musteri mehdudiyyeti', N'Xususi kod musteri mehdudiyyeti (musteri)', N'C:\TayqaSale\ExcelTemplates\Xususi kod musteri mehdudiyyeti (musteri)_350B12A058B742F9B19894014F976700.xlsx', 2);
INSERT INTO dbo.SYS_ExcelTemplate (Name, Description, FilePath, ModuleId) VALUES (N'Xususi kod musteri mhdudiyyeti', N'Xususi kod musteri mehdudiyyeti (umumi)', N'C:\TayqaSale\ExcelTemplates\Xususi kod musteri mhdudiyyeti (umumi)_D382365C337B49A79DB054A8AB1E128E.xlsx', 2);