CREATE procedure [dbo].[SP_CHL_GetUserDynamicSurveyQuestions] @surveyId int, @clientId int
as
begin
    -- must be customized for client

    select cast(0 as bit)      as IsAnswerRequired,
           cast(1 as tinyint)  as QuestionType,
           cast(1 as smallint) as QuestionOrderNumber,
           ''                  as QuestionName,
           ''                  as QuestionCode,
           ''                  as QuestionDescription,
           null                as ReasonConditionType,
           null                as ReasonConditionValue,
           cast(1 as tinyint)  as ReasonInputType,
           cast(0 as tinyint)  as QuestionStatus,
           cast(1 as tinyint)  as WeightingType,
           cast(0 as float)    as AnswerMinValue,
           cast(0 as float)    as AnswerMaxValue,
           null                as ItemId,
           null                as ItemGroupId,
           cast(1 as tinyint)  as PhotoUploadOption,
           cast(1 as tinyint)  as QuestionReasonSelectOption,
           cast(2 as tinyint)  as AnswerInputType,
           null                as QuestionGroupCode,
           null                as QuestionGroupName,
           null                as QuestionGroupDescription,
           null                as AnswerText,
           null                as AnswerReasonSelectOption,
           null                as AnswerReasonInputType,
           null                as AnswerPhotoUploadOption,
           cast(0 as bit)      as IsCorrect,
           null                as AnswerOrderNumber,
           9                   as AnswerTypeId,
           'Selection'         as AnswerTypeName,
           cast(0 as bit)      as IsAnswerFree,
           null                as QuestionAttachmentId,
           null                as QuestionAttachmentUrl,
           null                as QuestionSecureUrl,
           null                as QuestionTagId,
           null                as QuestionTag,
           null                as AnswerSelectReasonId,
           null                as AnswerSelectReasonName,
           null                as AnswerSelectReasonDescription,
           cast(3 as tinyint)  as AnswerSelectReasonType,
           cast(2 as tinyint)  as AnswerSelectSelectionType,
           cast(0 as tinyint)  as AnswerSelectMandatoryType,
           null                as ReasonId,
           null                as CustomReasonInputType,
           null                as MandatoryType,
           null                as ReasonType,
           null                as ReasonValue,
           null                as SelectionType,
           null                as ReasonLabel
end
go