CREATE NONCLUSTERED INDEX [IX_MD_Route_Firm_Status] ON [dbo].[MD_Route]
(
	[Status] ASC,
	[Firm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


