ALTER function [dbo].[FN_TS_MasterData_GetClientDebt_XXX_YY]()
RETURNS TABLE
AS RETURN
(
SELECT CARDREF AS ClientId, 1 AS OrderNo, TOTTYP AS CurrencyType, ROUND(SUM(DEBIT),2) AS Debit, ROUND(SUM(CREDIT),2) AS Credit 
FROM LV_XXX_YY_GNTOTCL WITH (NOLOCK)
WHERE CARDREF IN (SELECT ClientId FROM FN_TS_MasterData_GetAllClient_XXX()) AND TOTTYP=1
GROUP BY CARDREF, TOTTYP
Union
SELECT  CLCARD.LOGICALREF AS ClientId, 2 AS OrderNo, 1 AS CurrencyType,
ISNULL(ROUND(SUM((CASE WHEN CLFLINE.DATE_<=DATEADD(DAY, -convert(int, right(PAYPLAN.code,len(PAYPLAN.code)-1)) , Getdate()) THEN 1 ELSE 0 END)*(CASE WHEN CLFLINE.SIGN=0 THEN 1 ELSE -1 END)*CLFLINE.AMOUNT),2),0) AS Debit,
ISNULL(ROUND(SUM((CASE WHEN CLFLINE.DATE_>DATEADD(DAY, -convert(int, right(PAYPLAN.code,len(PAYPLAN.code)-1)) , Getdate())AND CLFLINE.SIGN=1 THEN 1 ELSE 0 END)*CLFLINE.AMOUNT),2),0) AS Credit
FROM LG_XXX_YY_CLFLINE CLFLINE WITH (NOLOCK) 
INNER JOIN LG_XXX_CLCARD CLCARD WITH (NOLOCK) ON (CLCARD.LOGICALREF=CLFLINE.CLIENTREF)
INNER JOIN LG_XXX_PAYPLANS  PAYPLAN WITH (NOLOCK)  ON (PAYPLAN.LOGICALREF=CLCARD.PAYMENTREF)
WHERE CLFLINE.CANCELLED=0 AND CLFLINE.STATUS=0
GROUP BY CLCARD.LOGICALREF
hAVING 
ROUND(ISNULL(SUM((CASE WHEN CLFLINE.DATE_<=DATEADD(DAY, -convert(int, right(PAYPLAN.code,len(PAYPLAN.code)-1)) , Getdate()) THEN 1 ELSE 0 END)*(CASE WHEN CLFLINE.SIGN=0 THEN 1 ELSE -1 END)*CLFLINE.AMOUNT),0)-
ISNULL(SUM((CASE WHEN CLFLINE.DATE_>DATEADD(DAY, -convert(int, right(PAYPLAN.code,len(PAYPLAN.code)-1)) , Getdate())AND CLFLINE.SIGN=1 THEN 1 ELSE 0 END)*CLFLINE.AMOUNT),0),2)>0.01
);
