CREATE Function [dbo].[FN_TS_MasterData_GetDeliveryOrder_XXX_YY](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT LINE.LOGICALREF AS OrderLineId, (CASE WHEN LINE.LINETYPE IN (0,6) THEN 0 WHEN LINE.LINETYPE=1 THEN 1 WHEN LINE.LINETYPE=2 THEN 2 END) AS LineType,
LINE.STOCKREF AS ItemId, UNITLINE.LOGICALREF AS ItemUnitId, UNITLINE.CODE AS ItemUnitCode,
LINE.AMOUNT AS Quantity, LINE.PRICE AS Price, 
(CASE WHEN LINE.LINETYPE IN (1,2) THEN  LINE.DISCPER ELSE ISNULL(DISCOUNTLINE.DISCPER ,0) END) AS DiscountPercent,                                             
ISNULL(CASE WHEN LINE.LINETYPE IN (1,2) THEN LINE.LINENET ELSE DISCOUNTLINE.LINENET END,0) AS DiscountAmount,
ISNULL(CASE WHEN LINE.LINETYPE IN (1) THEN LINE.LINENET-LINE.LINENET*LINE.DISCPER/100  WHEN LINE.LINETYPE IN (0,6) THEN LINE.LINENET-ISNULL(DISCOUNTLINE.LINENET ,0) END,0) AS NetTotal,
LINE.VATAMNT AS VatAmount, LINE.VATINC AS IsVatIncluded, LINE.VAT As VatRate,
ORFICHE.LOGICALREF AS OrderId, FICHENO AS OrderFicheNo, ORFICHE.CLIENTREF AS ClientId, ORFICHE.DATE_ AS OrderDate,
ORFICHE.SOURCEINDEX AS WarehouseNr, ORFICHE.BRANCH AS Division, ORFICHE.DEPARTMENT As Department, ORFICHE.FACTORYNR AS Factory, 
ORFICHE.SPECODE AS Specode, GENEXP1 AS Note, GENEXP2 AS Specode2, GENEXP3 AS Specode3, GENEXP4 AS Specode4, GENEXP5 AS Specode5,
TRADINGGRP AS TradingGroup, DOCTRACKINGNR AS DockTrackingNo, ORFICHE.STATUS AS OrderStatus, ORFICHE.AFFECTCOLLATRL AS OptAffectCollatrl, 
ORFICHE.SALESMANREF AS SalesmanId, ORFICHE.PAYDEFREF AS PaymentPlanId, TOTALDISCOUNTS AS TotalDiscounts, CAPIBLOCK_CREADEDDATE AS CreatedDate, CAPIBLOCK_MODIFIEDDATE AS ModifiedDate,
DOCODE AS Docode
FROM LG_XXX_YY_ORFLINE LINE WITH (NOLOCK) 
LEFT JOIN LG_XXX_UNITSETL UNITLINE WITH (NOLOCK) ON UNITLINE.LOGICALREF=LINE.UOMREF
LEFT JOIN LG_XXX_YY_ORFLINE DISCOUNTLINE WITH (NOLOCK) ON (DISCOUNTLINE.ORDFICHEREF=LINE.ORDFICHEREF AND DISCOUNTLINE.LINETYPE = 2 AND DISCOUNTLINE.GLOBTRANS=0 AND LINE.LOGICALREF=DISCOUNTLINE.PARENTLNREF)
INNER JOIN LG_XXX_YY_ORFICHE ORFICHE WITH (NOLOCK) ON ORFICHE.LOGICALREF = LINE.ORDFICHEREF
WHERE LINE.LINETYPE in (0,1,6) AND ORFICHE.STATUS=4 
AND ((CAPIBLOCK_CREADEDDATE >=@beginDate AND CAPIBLOCK_CREADEDDATE <=@endDate) OR (CAPIBLOCK_MODIFIEDDATE>=@beginDate AND CAPIBLOCK_MODIFIEDDATE<=@endDate)) 
);
GO
