CREATE Function [dbo].[FN_TS_Delivery_GetInvoice_XXX_YY](@erpId int)
RETURNS TABLE
AS RETURN
(
SELECT CLIENTREF As ClientId, BRANCH AS Division, SOURCEINDEX AS Warehouse, DEPARTMENT As Department, FACTORYNR AS Factory, TRADINGGRP AS TradingGroup, 
SPECODE AS Specode, GENEXP1 AS Note, GENEXP2 AS Specode2, GENEXP3 AS Specode3, GENEXP4 AS Specode4, '' AS Specode5, SALESMANREF As SalesmanId, 
AFFECTCOLLATRL As AffectCollatrl, STATUS AS Status, DATE_ AS Date, DOCTRACKINGNR AS DocktrackinNo, CAPIBLOCK_CREADEDDATE AS CreatedDate,
FICHENO AS FicheNo, TOTALDISCOUNTS AS TotlaDiscounts
FROM LG_XXX_YY_INVOICE WITH (NOLOCK) WHERE LOGICALREF=@erpId
);

GO
