CREATE Function [dbo].[FN_TS_Report_SaleInvoiceInfoForReturn_XXX_YY](@clientId int, @itemId int)
RETURNS TABLE
AS RETURN
(
--SELECT InvoiceId, InvoiceNo, Date, SaleQuantity, SaleQuantity as AllowedReturnQuantity, ItemUnitName, Price
                         --       FROM TayqaMobileApp..MOCK_DATA

select STLINE.LOGICALREF AS InvoiceId, INVOICE.FICHENO AS InvoiceNo ,INVOICE.DATE_ AS Date, 
--STLINE.AMOUNT AS SaleQuantity,  

STLINE.AMOUNT* (CASE WHEN STLINE.UINFO2=0 THEN 1 ELSE STLINE.UINFO2 END)/(CASE WHEN STLINE.UINFO1=0 THEN 1 ELSE STLINE.UINFO1 END)  AS SaleQuantity,
(STLINE.AMOUNT-STLINE.RETAMOUNT )* (CASE WHEN STLINE.UINFO2=0 THEN 1 ELSE STLINE.UINFO2 END)/(CASE WHEN STLINE.UINFO1=0 THEN 1 ELSE STLINE.UINFO1 END)  AS AllowedReturnQuantity, UNITSEL.NAME AS ItemUnitName,
--STLINE.AMOUNT-STLINE.RETAMOUNT AS AllowedReturnQuantity,  
--STLINE.PRICE AS Price 
STLINE.PRICE/(CASE WHEN STLINE.UINFO2=0 THEN 1 ELSE STLINE.UINFO2 END)/(CASE WHEN STLINE.UINFO1=0 THEN 1 ELSE STLINE.UINFO1 END) AS Price
--INVOICE.LOGICALREF AS InvoiceId,
from LG_XXX_YY_STLINE STLINE WITH (NOLOCK)
INNER JOIN LG_XXX_YY_STFICHE STFICHE WITH (NOLOCK) ON STFICHE.LOGICALREF=STLINE.STFICHEREF
INNER JOIN  LG_XXX_YY_INVOICE INVOICE WITH (NOLOCK) ON INVOICE.LOGICALREF=STFICHE.INVOICEREF
INNER JOIN LG_XXX_ITMUNITA ITMUNITA WITH (NOLOCK) ON ITMUNITA.ITEMREF=STLINE.STOCKREF AND ITMUNITA.LINENR=1
INNER JOIN LG_XXX_UNITSETL UNITSEL WITH (NOLOCK) ON UNITSEL.LOGICALREF=ITMUNITA.UNITLINEREF
 WHERE STLINE.TRCODE IN (7,8) AND STLINE.CANCELLED=0 AND STLINE.LINETYPE=0 AND STLINE.AMOUNT<>STLINE.RETAMOUNT AND STLINE.STOCKREF=@itemId AND STLINE.CLIENTREF=@clientId and INVOICE.DATE_<=Getdate()
 )

GO
