create Function [dbo].[FN_TS_MasterData_GetPaymentPlan_XXX](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT LOGICALREF AS PaymentPlanId, CODE AS Code, DEFINITION_ AS Name, SPECODE AS Specode, CYPHCODE AS CyphCode, WRKDAYS As WorkDays, ACTIVE AS Status,
CAPIBLOCK_CREADEDDATE AS CreatedDate, CAPIBLOCK_MODIFIEDDATE As ModifiedDate
FROM LG_XXX_PAYPLANS WITH (NOLOCK) 
WHERE ((CAPIBLOCK_CREADEDDATE >=@beginDate AND CAPIBLOCK_CREADEDDATE <=@endDate ) OR (CAPIBLOCK_MODIFIEDDATE>=@beginDate AND CAPIBLOCK_MODIFIEDDATE<=@endDate))
);

GO
