CREATE Function [dbo].[FN_TS_Report_GetGroupClientDebt_XXX_YY](@groupClientId int)
RETURNS TABLE
AS RETURN
(
Select CLCARD.LOGICALREF As ClientId, CLCARD.CODE As ClientCode, CLCARD.DEFINITION_ As ClientName, 
PCARD.EDINO As Edino, GNTOTCL.DEBIT As Debit, GNTOTCL.CREDIT As Credit, CLCARD.CITY AS City, CLCARD.SPECODE AS Specode, 162 As CurrencyType,'AZN' As CurrencyCode, 1 AS OrderNo
FROM LV_XXX_YY_GNTOTCL GNTOTCL WITH (NOLOCK)
Inner Join LG_XXX_CLCARD CLCARD WITH (NOLOCK) ON GNTOTCL.CARDREF = CLCARD.LOGICALREF
Left Join LG_XXX_CLCARD PCARD WITH (NOLOCK) ON CLCARD.PARENTCLREF = PCARD.LOGICALREF
Where GNTOTCL.TOTTYP = 1 AND CLCARD.PARENTCLREF=@groupClientId
);

GO
