CREATE Function [dbo].[FN_TS_Report_GetItemExtract_XXX_YY](@beginDate datetime, @endDate datetime, @itemId int)
RETURNS TABLE
AS RETURN
(
Select  
CLCARD.LOGICALREF AS ClientId,
LINE.TRCODE As Trcode,
LINE.TRCODE As OperationType,
LINE.DATE_ As Date, 
MAN.CODE As SalesmanCode,
MAN.DEFINITION_ As SalesmanName,
CLCARD.CODE As  ClientCode,
CLCARD.DEFINITION_ As ClientName,
LINE.AMOUNT AS Amount,
LINE.AMOUNT AS Quantity,
LINE.VATAMNT+LINE.VATMATRAH AS LineNet, 
LINE.VATAMNT+LINE.VATMATRAH AS LineTotal, 
UNITLINE.CODE As ItemUnitCode,
'AZN' As CurrencyCode
From LG_XXX_YY_STLINE LINE WITH (NOLOCK)
Inner Join LG_XXX_ITEMS ITEM WITH (NOLOCK) ON ITEM.LOGICALREF = LINE.STOCKREF 
Inner Join LG_XXX_CLCARD CLCARD WITH (NOLOCK) ON CLCARD.LOGICALREF = LINE.CLIENTREF
Left Join LG_SLSMAN MAN WITH (NOLOCK) ON MAN.LOGICALREF = LINE.SALESMANREF
Left Join LG_XXX_UNITSETL UNITLINE WITH (NOLOCK) ON UNITLINE.LOGICALREF = LINE.UOMREF
Where LINE.STATUS = 0 And LINE.DATE_ Between @beginDate And @endDate 
And LINE.TRCODE IN (2,3,7,8) And ITEM.LOGICALREF = @itemId

);

GO
