CREATE Function [dbo].[FN_TS_Report_GetOrderLine_XXX_YY](@orderId int )
RETURNS TABLE
AS RETURN
(
SELECT LINE.ORDFICHEREF AS OrderId, ITEM.LOGICALREF AS ItemId, ITEM.CODE AS ItemCode, ITEM.Name AS ItemName, UNITLINE.NAME AS UnitName,
LINE.LINETYPE AS LineType, LINE.AMOUNT AS Quantity, (CASE WHEN LINE.VATINC =1 THEN LINE.PRICE ELSE LINE.PRICE*(1+LINE.VAT/100)  END) AS Price, 
(CASE WHEN LINE.LINETYPE=1 THEN 0 ELSE (LINE.LINENET+LINE.VATAMNT-LINE.DISTDISC) END) AS Total,'AZN' As CurrencyCode
FROM LG_XXX_YY_ORFLINE LINE WITH (NOLOCK)
LEFT JOIN LG_XXX_ITEMS ITEM WITH (NOLOCK) ON LINE.STOCKREF = ITEM.LOGICALREF
LEFT JOIN LG_XXX_UNITSETL UNITLINE WITH (NOLOCK) ON UNITLINE.LOGICALREF=LINE.UOMREF
WHERE LINE.LINETYPE in (0,1,6) AND LINE.ORDFICHEREF=@orderId
);

GO
