create function [dbo].[FN_TS_MasterData_GetProject_XXX](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT LOGICALREF AS ProjectId, CODE AS Code, ACTIVE As Status, NAME AS Name, CAPIBLOCK_CREADEDDATE AS CreatedDate, CAPIBLOCK_MODIFIEDDATE AS ModifiedDate
FROM LG_XXX_PROJECT WITH (NOLOCK) 
WHERE ((CAPIBLOCK_CREADEDDATE >=@beginDate AND CAPIBLOCK_CREADEDDATE <=@endDate) OR (CAPIBLOCK_MODIFIEDDATE>=@beginDate AND CAPIBLOCK_MODIFIEDDATE<=@endDate))
);