Create Function [dbo].[FN_TS_Report_GetInvoiceDetail_XXX_YY](@invoiceId int)
RETURNS TABLE
AS RETURN
(
WITH 
UMUMI as (SELECT LINE.logIcalref,LINE.LINETYPE as 'ltype',LINE.globtrans,LINE.DISCPER,
LINE.LINETYPE AS LineTypeId, LINE.TOTAL 'total',
ITEM.LOGICALREF AS ItemId, ITEM.CODE AS ItemCode, ITEM.Name AS ItemName,  ITMBARCODE.BARCODE AS Barcode,
LINE.AMOUNT AS Quantity,
UNITLINE.CODE AS ItemUnitCode,
UNITLINE.NAME AS UnitName,
LINE.PRICE AS Price, 
ISNULL(CASE WHEN LINE.LINETYPE IN (1) THEN LINE.LINENET-LINE.LINENET*LINE.DISCPER/100  WHEN LINE.LINETYPE=0 THEN LINE.LINENET END,0) AS NetTotal,
LINE.VATAMNT AS VatAmount, LINE.VATINC,
'AZN' AS Currency
FROM LG_XXX_YY_STLINE LINE WITH (NOLOCK)
LEFT JOIN LG_XXX_ITEMS ITEM WITH (NOLOCK) ON LINE.STOCKREF = ITEM.LOGICALREF
LEFT JOIN LG_XXX_UNITSETL UNITLINE WITH (NOLOCK) ON UNITLINE.LOGICALREF=LINE.UOMREF
LEFT JOIN LG_XXX_ITMUNITA ITEMUNITEDED WITH (NOLOCK) ON (ITEMUNITEDED.ITEMREF=ITEM.LOGICALREF AND ITEMUNITEDED.LINENR=1)
LEFT JOIN LG_XXX_UNITBARCODE ITMBARCODE WITH (NOLOCK) ON (ITMBARCODE.ITEMREF=LINE.STOCKREF AND ITMBARCODE.LINENR=1 AND ITMBARCODE.UNITLINEREF=ITEMUNITEDED.UNITLINEREF)
WHERE LINE.INVOICEREF= @invoiceId AND (LINE.LINETYPE in (0,1,6) OR (LINE.LINETYPE IN (2) AND LINE.GLOBTRANS=1))),
ENDIRIM as (select PARENTLNREF,sum(TOTAL) 'ENDIRIMSUM',sum(DISCPER) 'ENDIRIMPER' FROM LG_XXX_YY_STLINE WITH (NOLOCK) WHERE 
INVOICEREF =@invoiceId and GLOBTRANS=0 and LINETYPE in (2) group by PARENTLNREF)

select UMUMI.LineTypeId AS LineType, UMUMI.ItemId AS ItemId, UMUMI.ItemCode AS ItemCode, UMUMI.ItemName AS ItemName, 
UMUMI.Barcode AS Barcode, UMUMI.Quantity AS Quantity, UMUMI.ItemUnitCode AS UnitCode, UMUMI.UnitName AS UnitName, UMUMI.Price AS Price,
case when UMUMI.ltype IN (2) and UMUMI.GLOBTRANS=1 then UMUMI.DISCPER else ENDIRIM.ENDIRIMPER end AS DiscountPercent,
case when UMUMI.ltype IN (2) and UMUMI.GLOBTRANS=1 then UMUMI.Total else  ENDIRIM.ENDIRIMSUM end AS DiscountAmount,
ISNULL(CASE WHEN UMUMI.ltype IN (1) THEN 0 WHEN UMUMI.ltype in (0,6) THEN UMUMI.total-isnull(ENDIRIM.ENDIRIMSUM,0) else UMUMI.total END,0) AS NetTotal, UMUMI.VatAmount AS VatAmount,
UMUMI.VATINC AS IsVatIncluded, UMUMI.Currency AS Currency
from UMUMI WITH (NOLOCK)
left join ENDIRIM WITH (NOLOCK) on UMUMI.LOGICALREF=ENDIRIM.PARENTLNREF


);

GO
