CREATE Function [dbo].[FN_TS_MasterData_GetBank_XXX] (@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT LOGICALREF As BankId, ACTIVE AS Status, Code As Code, DEFINITION_ As Name, BRANCH AS Branch, SPECODE AS Specode, BRANCHNO AS BranchNo, COUNTRY AS Country, CITY AS City, ADDR1 AS Address1, ADDR2 AS Address2, 
POSTCODE AS PostCode, TELNRS1 As TelNo, FAXNR AS FaxNo, INCHARGE AS Incharge, EMAILADDR AS Email, WEBADDR AS WebUrl, CORRPACC AS CorpAccount,   
CAPIBLOCK_CREADEDDATE As CreatedDate, CAPIBLOCK_MODIFIEDDATE AS ModifiedDate
FROM LG_XXX_BNCARD WITH (NOLOCK)
WHERE ((CAPIBLOCK_CREADEDDATE >=@beginDate AND CAPIBLOCK_CREADEDDATE <=@endDate)
OR (CAPIBLOCK_MODIFIEDDATE>=@beginDate AND CAPIBLOCK_MODIFIEDDATE<=@endDate))
);
GO
