CREATE Function [dbo].[FN_TS_MasterData_GetAllItem_XXX] ()
RETURNS TABLE
AS RETURN
(SELECT LOGICALREF AS ItemId, CAPIBLOCK_CREADEDDATE AS CreatedDate, CAPIBLOCK_MODIFIEDDATE As ModifiedDate  FROM LG_XXX_ITEMS WITH (NOLOCK)
WHERE CARDTYPE IN (1,2,3,4,12,13))
GO
