CREATE Function [dbo].[FN_TS_Report_GetOrderStatus_XXX_YY](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
Select ORFICHE.LOGICALREF AS OrderId, ORFICHE.FICHENO AS OrderNo, ORFICHE.DATE_ AS OrderDate, 
ORFICHE.NETTOTAL AS NetTotal, SLSMAN.LOGICALREF AS SalesmanId, SLSMAN.DEFINITION_ AS SalesmanName,
SLSMAN.CODE AS SalesmanCode, Case ORFICHE.STATUS WHEN 4 Then 1 WHEN 2 THEN 0 WHEN 1 THEN 2 End AS OrderStatus,
CARD.CODE AS ClientCode, CARD.SPECODE4 AS ClientSpecode4, ORFICHE.CLIENTREF AS ClientId, CARD.DEFINITION_ AS ClientName,
'AZN' As CurrencyCode
From LG_XXX_YY_ORFICHE ORFICHE With (NoLock)
Inner Join LG_XXX_CLCARD CARD With (NoLock) On CARD.LOGICALREF = ORFICHE.CLIENTREF
INNER JOIN LG_SLSMAN SLSMAN ON SLSMAN.LOGICALREF = ORFICHE.SALESMANREF
Where ORFICHE.STATUS IN (1,2,4) AND ORFICHE.DATE_ Between @beginDate And @endDate 
);

GO
