CREATE Function [dbo].[FN_TS_Report_GetClientBalance_XXX_YY](@clientId int, @date datetime)
RETURNS @Temp TABLE (Balance float)
AS 
begin
if (@date<'2021-01-01')
begin
insert into @Temp
SELECT ISNULL(SUM((CASE WHEN CLFLINE.SIGN=0 THEN 1 ELSE -1 END)*CLFLINE.AMOUNT),0) As Balance
FROM LG_XXX_05_CLFLINE CLFLINE WITH (NOLOCK) 
WHERE CLFLINE.DATE_ < @date AND CLFLINE.CLIENTREF = @clientId AND CLFLINE.CANCELLED=0 AND CLFLINE.STATUS=0
end
else
begin
insert into @Temp
SELECT ISNULL(SUM((CASE WHEN CLFLINE.SIGN=0 THEN 1 ELSE -1 END)*CLFLINE.AMOUNT),0) As Balance
FROM LG_XXX_YY_CLFLINE CLFLINE WITH (NOLOCK) 
WHERE CLFLINE.DATE_ < @date AND CLFLINE.CLIENTREF = @clientId AND CLFLINE.CANCELLED=0 AND CLFLINE.STATUS=0
end
return
end

GO
