CREATE Function [dbo].[FN_TS_MasterData_GetItemUnit_XXX](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT UNIT.LOGICALREF AS UnitId, ITEM.ItemId AS ItemId, UNITSEL.CODE AS UnitCode, UNITSEL.NAME AS UnitName,
UNITSEL.MAINUNIT AS IsMaintUnit, UNITSEL.LINENR AS LineNr, UNIT.WIDTH AS Width, UNIT.LENGTH AS Length, UNIT.HEIGHT AS Height, 
UNIT.AREA AS Area, UNIT.GROSSVOLUME AS GrossVolume, UNIT.GROSSWEIGHT AS GrossWeight,UNIT.CONVFACT1 AS Convfact1,UNIT.CONVFACT2 As Convfact2,
UNIT.PURCHCLAS AS IsForPurchase, UNIT.SALESCLAS IsForSale, UNIT.SALESCLAS IsForReturn, 
UNIT.PURCHPRIORTY AS PurchasePriority, UNIT.SALESPRIORITY AS SalePriority, UNIT.SALESPRIORITY AS ReturnPriority
FROM LG_XXX_ITMUNITA UNIT WITH (NOLOCK) 
INNER JOIN FN_TS_MasterData_GetAllItem_XXX() ITEM ON (ITEM.ItemId=UNIT.ITEMREF  AND ((ITEM.CreatedDate >=@beginDate  AND ITEM.CreatedDate <=@endDate) OR (ITEM.ModifiedDate>=@beginDate AND ITEM.ModifiedDate<=@endDate)))
INNER JOIN LG_XXX_UNITSETL UNITSEL WITH (NOLOCK) ON UNITSEL.LOGICALREF=UNIT.UNITLINEREF);

GO
