CREATE Function [dbo].[FN_TS_Integration_GetOrder_XXX_YY](@orderId int)
RETURNS TABLE
AS RETURN
(
SELECT LOGICALREF AS OrdRef, FICHENO As FicheNo, NETTOTAL As NetTotal, TOTALDISCOUNTS AS TotalDiscount, TOTALDISCOUNTS-TOTALPROMOTIONS AS DiscountAmount, 
STATUS AS Status, TOTALVAT AS TotalVat, GROSSTOTAL AS GrossTotal
FROM LG_XXX_YY_ORFICHE WITH (NOLOCK) 
WHERE LOGICALREF=@orderId
);

GO
