CREATE Function [dbo].[FN_TS_MasterData_GetAllClient_XXX] ()
RETURNS TABLE
AS RETURN
(SELECT LOGICALREF AS ClientId, CAPIBLOCK_CREADEDDATE AS CreatedDate, CAPIBLOCK_MODIFIEDDATE As ModifiedDate  FROM LG_XXX_CLCARD WITH (NOLOCK) 
WHERE CARDTYPE IN (3,4))
GO
