CREATE Function [dbo].[FN_TS_MasterData_GetSalesmanClientMapping_XXX]()
RETURNS TABLE
AS RETURN
(
SELECT DISTINCT SALESMANREF AS SalesmanId, CLIENTREF AS ClientId FROM LG_XXX_SLSCLREL WITH (NOLOCK) WHERE SALESMANREF>0
);

GO
