CREATE Function [dbo].[FN_TS_MasterData_GetItem_XXX](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT ITEM.LOGICALREF AS ItemId, ITEM.ACTIVE AS Status, ITEM.CARDTYPE AS CardType, ITEM.CODE AS Code, ITEM.NAME AS Name, ITEM.STGRPCODE AS GroupCode, 
ISNULL(GRP.DEFINITION_,'') AS GroupName, ISNULL(PROD.SPECODE,'') AS ProducerCode, ISNULL(PROD.DEFINITION_,'') AS ProducerName, 
ITEM.SPECODE AS Specode, ISNULL(SPE.DEFINITION_,'') AS SpecodeDesc, ITEM.SPECODE2 AS Specode2, ISNULL(SPE2.DEFINITION_,'') AS Specode2Desc,
ITEM.SPECODE3 As Specode3, ISNULL(SPE3.DEFINITION_,'') AS Specode3Desc, ITEM.SPECODE4 AS Specode4, ISNULL(SPE4.DEFINITION_,'') AS Specode4Desc,
ITEM.SPECODE5 AS Specode5, ISNULL(SPE5.DEFINITION_,'') AS Specode5Desc, ITEM.CYPHCODE AS AuthCode, ISNULL(AUTH.DEFINITION_,'') AS AuthCodeDesc,
ITEM.VAT AS Vat,ITEM.SELLVAT AS SellVat,ITEM.RETURNVAT AS ReturnVat,ITEM.SELLPRVAT AS SellRetailVat, ITEM.RETURNPRVAT AS ReturnRetailVat,
ITEM.CAPIBLOCK_CREADEDDATE AS CreatedDate, ITEM.CAPIBLOCK_MODIFIEDDATE As ModifiedDate, MARK.CODE AS BrendCode, MARK.DESCR AS BrendName
FROM LG_XXX_ITEMS ITEM WITH (NOLOCK)
LEFT JOIN LG_XXX_SPECODES SPE WITH(NOLOCK) ON SPE.SPECODE=ITEM.SPECODE and SPE.SPETYP1=1 and SPE.CODETYPE=1 and SPE.SPECODETYPE=1
LEFT JOIN LG_XXX_SPECODES SPE2 WITH(NOLOCK) ON SPE2.SPECODE=ITEM.SPECODE2 and SPE2.SPETYP2=1 and SPE2.CODETYPE=1 and SPE2.SPECODETYPE=1
LEFT JOIN LG_XXX_SPECODES SPE3 WITH(NOLOCK) ON SPE3.SPECODE=ITEM.SPECODE3 and SPE3.SPETYP3=1 and SPE3.CODETYPE=1 and SPE3.SPECODETYPE=1
LEFT JOIN LG_XXX_SPECODES SPE4 WITH(NOLOCK) ON SPE4.SPECODE=ITEM.SPECODE4 and SPE4.SPETYP4=1 and SPE4.CODETYPE=1 and SPE4.SPECODETYPE=1
LEFT JOIN LG_XXX_SPECODES SPE5 WITH(NOLOCK) ON SPE5.SPECODE=ITEM.SPECODE5 and SPE5.SPETYP5=1 and SPE5.CODETYPE=1 and SPE5.SPECODETYPE=1
LEFT JOIN LG_XXX_SPECODES AUTH WITH(NOLOCK) ON AUTH.SPECODE=ITEM.CYPHCODE and AUTH.CODETYPE=2 and AUTH.SPECODETYPE=1
LEFT JOIN LG_XXX_SPECODES GRP WITH(NOLOCK) ON GRP.SPECODE=ITEM.STGRPCODE  and GRP.CODETYPE=4 and GRP.SPECODETYPE=0
LEFT JOIN LG_XXX_SPECODES PROD WITH(NOLOCK) ON ITEM.ISONR = PROD.SPECODE AND PROD.SPECODETYPE=1 AND PROD.CODETYPE=7
LEFT JOIN LG_XXX_MARK MARK WITH(NOLOCK) ON ITEM.MARKREF = MARK.LOGICALREF
WHERE ((ITEM.CAPIBLOCK_CREADEDDATE >=@beginDate  AND ITEM.CAPIBLOCK_CREADEDDATE <=@endDate) OR (ITEM.CAPIBLOCK_MODIFIEDDATE>=@beginDate AND ITEM.CAPIBLOCK_MODIFIEDDATE<=@endDate))
AND ITEM.CARDTYPE IN (1,2,3,4,12,13)
);

GO
