CREATE Function [dbo].[FN_TS_MasterData_GetSalesman](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT LOGICALREF AS SalesmanId, CODE AS Code, ACTIVE AS STATUS, DEFINITION_ AS NAME, FIRMNR AS Firm, DIVISID AS DivisionNr, 
(CASE WHEN POSITION_ = '' OR POSITION_ IS NULL THEN NULL
WHEN POSITION_ IN ('YY') THEN 1
WHEN POSITION_ IN ('10') THEN 2
WHEN POSITION_ IN ('11') THEN 3
WHEN POSITION_ IN ('12') THEN 4
WHEN POSITION_ IN ('05') THEN 5
ELSE NULL END) AS PositionId,
CAPIBLOCK_CREADEDDATE AS CreatedDate, CAPIBLOCK_MODIFIEDDATE AS ModifiedDate
FROM LG_SLSMAN WITH (NOLOCK)
WHERE ((CAPIBLOCK_CREADEDDATE >=@beginDate AND CAPIBLOCK_CREADEDDATE <=@endDate) OR (CAPIBLOCK_MODIFIEDDATE>=@beginDate AND CAPIBLOCK_MODIFIEDDATE<=@endDate))

);

GO
