CREATE Function [dbo].[FN_TS_Report_GetClientSpecialExtract_XXX_YY](@clientId int, @beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(

With Extension As (Select CLFLINE.DATE_ As FICHE_DATE, IsNull(PCARD.EDINO,'') As EDINO, CLFLINE.LINEEXP, CLFLINE.DOCODE,
CLCARD.CODE As CLIENT_CODE, CLCARD.DEFINITION_ As CLIENT_NAME, CLFLINE.TRANNO As FICHENO, CLFLINE.TRCODE,                               
Case When CLFLINE.SIGN=0 Then CLFLINE.AMOUNT ELSE 0 END As DEBIT,
Case When CLFLINE.SIGN=1 Then CLFLINE.AMOUNT ELSE 0 END As CREDIT,
Case When (CLFLINE.MODULENR = 4 And INVOICE.SOURCEINDEX In (Select NR From L_CAPIWHOUSE Where SITEID = 1)) Or CLFLINE.MODULENR = 7
Then 'R' Else 'Q' End As 'FINANCE_TYPE',
CLFLINE.AMOUNT As AMOUNT, CLFLINE.SALESMANREF
From LG_XXX_YY_CLFLINE CLFLINE WITH (NOLOCK)
Left Join LG_XXX_YY_INVOICE INVOICE WITH (NOLOCK) On INVOICE.LOGICALREF = CLFLINE.SOURCEFREF And MODULENR = 4
Inner Join LG_XXX_CLCARD CLCARD WITH (NOLOCK) On CLFLINE.CLIENTREF = CLCARD.LOGICALREF
Left Join LG_XXX_CLCARD PCARD WITH (NOLOCK) On PCARD.LOGICALREF = CLCARD.PARENTCLREF
Where CLFLINE.CANCELLED = 0 And CLFLINE.DATE_ Between @beginDate And @endDate And CLCARD.LOGICALREF = @clientId)

Select Extension.TRCODE AS Trcode, Extension.FICHE_DATE AS FicheDate, Extension.EDINO AS Edino, 
Extension.CLIENT_CODE AS ClientCode, Extension.CLIENT_NAME AS ClientName,
Extension.FICHENO AS FicheNo, Extension.AMOUNT AS Amount, Extension.LINEEXP AS LineDesc, Extension.DOCODE AS Docode, Extension.DEBIT As Debit, Extension.CREDIT AS Credit,
MAN.CODE AS SalesmanCode, MAN.DEFINITION_ AS SalesmanName,  'AZN' As CurrencyCode
From Extension WITH (NOLOCK)
LEFT JOIN LG_SLSMAN MAN WITH (NOLOCK) ON MAN.LOGICALREF=Extension.SALESMANREF
Where Extension.FINANCE_TYPE = 'R'

);

GO
