CREATE OR ALTER PROCEDURE [dbo].[SP_WPM_PreTaskCreation]
    @currentUserId INT,
    @firm SMALLINT,
    @name NVARCHAR(255) null,
    @message NVARCHAR(1000) null,
    @isGpsStartRestricted BIT null,
    @isGpsStopRestricted BIT null,
    @priority TINYINT null,
    @type TINYINT null,
    @clientListType TINYINT null,
    @isClientOrderRequired BIT null,
    @isOptional BIT null,
    @categoryId INT null,
    @subcategoryId INT null,
    @groupId INT null,
    @confirmationType TINYINT,
    @users NVARCHAR(MAX) null,
    @scheduleStartDate DATETIME null,
    @scheduleEndDate DATETIME null,
    @scheduleStartTime TIME null,
    @scheduleEndTime TIME null
AS
BEGIN
    SELECT 
        @currentUserId AS CurrentUserId,
        @firm AS Firm,
        @name AS Name,
        @message AS Message,
        ISNULL(@isGpsStartRestricted, 0) AS IsGpsStartRestricted,
        ISNULL(@isGpsStopRestricted, 0) AS IsGpsStopRestricted,
        ISNULL(@priority, 2) AS Priority,
        ISNULL(@type, 5) AS Type,
        ISNULL(@clientListType, 2) AS ClientListType,
        ISNULL(@isClientOrderRequired, 0) AS IsClientOrderRequired,
        ISNULL(@isOptional, 0) AS IsOptional,
        ISNULL(@categoryId, 0) AS CategoryId,
        ISNULL(@subcategoryId, 0) AS SubcategoryId,
        ISNULL(@groupId, 0) AS GroupId,
        @confirmationType AS ConfirmationType,
        @users AS Users,
        ISNULL(@scheduleStartDate, GETDATE()) AS ScheduleStartDate,
        ISNULL(@scheduleEndDate, GETDATE()) AS ScheduleEndDate,
        ISNULL(@scheduleStartTime, '00:00:00') AS ScheduleStartTime,
        ISNULL(@scheduleEndTime, '23:59:59') AS ScheduleEndTime;
END