ALTER TABLE MD_ClientShipInfo ADD Type TINYINT GO
ALTER TABLE MD_ClientShipInfo ADD Address NVARCHAR(500) GO
ALTER TABLE MD_ClientShipInfo ADD Latitude FLOAT GO
ALTER TABLE MD_ClientShipInfo ADD Longitude FLOAT GO
ALTER TABLE MD_ClientShipInfo ADD Note NVARCHAR(MAX) GO