CREATE TABLE SYS_DynamicAPI(
Id INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(100),
Code NVARCHAR(100),
URL NVARCHAR (MAX),
HTTPRequestType TinyInt,
IdentificationType TinyInt,
SqlQuery NVARCHAR(MAX),
UserName NVARCHAR(100),
Password NVARCHAR(100),
CreatorUserId BIGINT NOT NULL,
CreationTime DATETIME,
LastModifierUserId BIGINT,
LastModificationTime DATETIME,
TenantId INT NOT NULL,
IsActive BIT,
IsDeleted BIT,
DeleterUserId BIGINT,
DeletionTime DATETIME,
)
