CREATE Function [dbo].[FN_TS_Integration_GetSaleInvoicesForSplitReturnInvoice_XXX_YY](@clientId int, @itemIds nvarchar(MAX), @isCustomPrice bit)
RETURNS TABLE
AS RETURN
(
SELECT 
STLINE.INVOICEREF AS InvoiceId,
INVOICE.FICHENO AS InvoiceNo,
STLINE.AMOUNT AS Quantity,
STLINE.STOCKREF AS ItemId,
STLINE.PRICE AS Price,
INVOICE.CAPIBLOCK_CREADEDDATE AS CreatedDate,
SERILOTN.CODE AS SerialNumber
FROM LG_XXX_YY_STLINE STLINE WITH (NOLOCK)
LEFT JOIN LG_XXX_YY_INVOICE INVOICE ON STLINE.INVOICEREF = INVOICE.LOGICALREF
left join LG_XXX_YY_SLTRANS SLTRANS ON SLTRANS.STTRANSREF = STLINE.LOGICALREF
LEFT JOIN LG_XXX_YY_SERILOTN SERILOTN ON SLTRANS.SLREF=SERILOTN.LOGICALREF
WHERE (STLINE.LINETYPE in (0,1,6) OR (STLINE.LINETYPE IN (2) AND STLINE.GLOBTRANS=1 )) 
AND STLINE.CLIENTREF = @clientId 
AND STLINE.STOCKREF IN (SELECT * FROM F_SplitList(@itemIds, ','))
AND INVOICE.CAPIBLOCK_CREADEDDATE >= 
  CASE WHEN @isCustomPrice = 1 THEN 
	'2000-01-01'
	ELSE
    DATEADD(day,-7, GETDATE())
  END
AND INVOICE.CAPIBLOCK_CREADEDDATE < GETDATE()
);