
/****** Object:  UserDefinedFunction [dbo].[FN_TS_Integration_GetWarehouseLineSerialNumbers_XXX_YY]    Script Date: 12/30/2021 12:58:02 PM ******/
CREATE Function [dbo].[FN_TS_Integration_GetWarehouseLineSerialNumbers_XXX_YY](@ficheId int)
RETURNS TABLE
AS RETURN
(
SELECT distinct LINE.STFICHEREF AS FicheRef, SERILOTN.CODE AS SerialNumber, LINE.STOCKREF AS ItemId
FROM LG_XXX_YY_STLINE LINE WITH (NOLOCK)
LEFT JOIN LG_XXX_YY_SLTRANS SLTRANS ON SLTRANS.STTRANSREF = LINE.LOGICALREF
LEFT JOIN LG_XXX_YY_SERILOTN SERILOTN ON SLTRANS.SLREF=SERILOTN.LOGICALREF
WHERE (LINE.LINETYPE in (0,1,6) OR (LINE.LINETYPE IN (2) AND LINE.GLOBTRANS=1 )) 
AND LINe.STFICHEREF=@ficheId and SERILOTN.CODE is not null
);
