
IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SYS_DynamicWebScreenCustomisedColumn'))
BEGIN
    DROP TABLE SYS_DynamicWebScreenCustomisedColumn;
END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SYS_DynamicWebScreenInnerQuery'))
BEGIN
    DROP TABLE SYS_DynamicWebScreenInnerQuery;
END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SYS_WebReportCustomisedColumn'))
BEGIN
    DROP TABLE SYS_WebReportCustomisedColumn;
END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SYS_DynamicWebScreenNonHeaderFilter'))
BEGIN
    DROP TABLE SYS_DynamicWebScreenNonHeaderFilter;
END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SYS_DynamicWebScreenUserMapping'))
BEGIN
    DROP TABLE SYS_DynamicWebScreenUserMapping;
END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SYS_SpecialReportUserMapping'))
BEGIN
    DROP TABLE SYS_SpecialReportUserMapping;
END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SYS_WebDetailReport'))
BEGIN
    DROP TABLE SYS_WebDetailReport;
END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SYS_WebReportNonHeaderFilter'))
BEGIN
    DROP TABLE SYS_WebReportNonHeaderFilter;
END

