
CREATE TABLE [dbo].[SYS_WebDetailReport](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DisplayLabel] [nvarchar](100) NOT NULL,
	[SqlQuery] [nvarchar](max) NOT NULL,
	[ParentId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
