
CREATE TABLE [dbo].[WPM_WorkExecutionClientMappingStatus](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TaskClientId] [int] NOT NULL,
	[Status] [tinyint] NOT NULL,
	[CreationTime] [datetime] NOT NULL,
	[CreatorUserId] [bigint] NULL,
 CONSTRAINT [PK__WPM_Work__3214EC07C6D76B78] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
