create   function [dbo].[FN_TS_MasterData_GetItemStock_XXX_YY]()
RETURNS TABLE
AS RETURN
(SELECT STOCKREF AS ItemId, INVENNO AS WarehouseNr, SUM(ONHAND) AS ActualStock, SUM(ONHAND-RESERVED) AS RealStock , SUM(ONHAND) AS SpecialStock
FROM LG_XXX_YY_GNTOTST  
WHERE INVENNO!=-1 AND STOCKREF IN (SELECT ItemId FROM FN_TS_MasterData_GetAllItem_XXX())   
GROUP BY STOCKREF, INVENNO
);
GO
