create   function [dbo].[FN_TS_MasterData_GetFactDistrubutedByUser_XXX_YY](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT YEAR(STLINE.DATE_) AS Year, MONTH(STLINE.DATE_) AS Month, STLINE.SALESMANREF AS SalesmanId, STLINE.STOCKREF AS ItemId, 
ITMUNITA.LOGICALREF AS ItemUnitId,
ROUND( SUM (( CASE WHEN STLINE.TRCODE IN (7,8) THEN 1 ELSE -1 END ) *STLINE.AMOUNT*
(CASE WHEN STLINE.UINFO2=0 THEN 1 ELSE STLINE.UINFO2 END)/(CASE WHEN STLINE.UINFO1=0 THEN 1 ELSE STLINE.UINFO1 END) ),2) AS  Quantity 
FROM  LG_XXX_YY_STLINE STLINE WITH (NOLOCK)
INNER JOIN LG_XXX_ITMUNITA ITMUNITA WITH (NOLOCK) ON ITMUNITA.ITEMREF=STLINE.STOCKREF AND ITMUNITA.LINENR=1
WHERE STLINE.TRCODE IN (7,8) AND STLINE.DATE_>=@beginDate AND STLINE.DATE_<@endDate AND STLINE.STATUS=0 AND STLINE.CANCELLED=0 AND STLINE.SALESMANREF>0
GROUP BY YEAR(STLINE.DATE_), MONTH(STLINE.DATE_), STLINE.SALESMANREF, STLINE.STOCKREF, ITMUNITA.LOGICALREF
);
GO
