create Function [dbo].[FN_TS_MasterData_GetCashCard_XXX] (@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT LOGICALREF AS CashCardId, CODE AS Code, NAME AS Name, ACTIVE AS Status, CAPIBLOCK_CREADEDDATE AS CreatedDate, CAPIBLOCK_MODIFIEDDATE AS ModifiedDate
FROM LG_XXX_KSCARD WITH (NOLOCK) 
WHERE ((CAPIBLOCK_CREADEDDATE >=@beginDate AND CAPIBLOCK_CREADEDDATE <=@endDate ) OR (CAPIBLOCK_MODIFIEDDATE>=@beginDate AND CAPIBLOCK_MODIFIEDDATE<=@endDate))
)
GO
