CREATE Function [dbo].[FN_TS_Report_GetAllClientDebt_XXX_YY]()
RETURNS TABLE
AS RETURN
(
Select CLCARD.LOGICALREF As ClientId, CLCARD.CODE As ClientCode, CLCARD.DEFINITION_ As ClientName,
PCARD.EDINO As Edino, GNTOTCL.DEBIT As Debit, GNTOTCL.CREDIT As Credit, CLCARD.CITY AS City, CLCARD.SPECODE AS Specode, 162 AS CurrencyType,  'AZN' As CurrencyCode
From LG_XXX_YY_GNTOTCL GNTOTCL WITH (NOLOCK)
Inner Join LG_XXX_CLCARD CLCARD WITH (NOLOCK) On GNTOTCL.CARDREF=CLCARD.LOGICALREF
Left Join LG_XXX_CLCARD PCARD WITH (NOLOCK) On CLCARD.PARENTCLREF=PCARD.LOGICALREF
Where GNTOTCL.TOTTYP = 1 
);
GO
