Create Function [dbo].[FN_TS_MasterData_GetBankAccount_XXX] (@beginDate datetime, @endDate datetime)
RETURNS TABLE 
AS RETURN
(
SELECT BANKREF AS BankId, LOGICALREF AS BankAccountId, CODE AS Code, DEFINITION_ AS Name, ACTIVE AS Status, CARDTYPE AS CardType, 
SPECODE AS Specode, CURRENCY AS Currency, ACCOUNTNO AS AccountNo, IBAN AS Iban,
CAPIBLOCK_CREADEDDATE AS CreatedDate, CAPIBLOCK_MODIFIEDDATE AS ModifiedDate
FROM LG_XXX_BANKACC WITH (NOLOCK)
WHERE ((CAPIBLOCK_CREADEDDATE >=@beginDate AND CAPIBLOCK_CREADEDDATE <=@endDate) OR (CAPIBLOCK_MODIFIEDDATE>=@beginDate AND CAPIBLOCK_MODIFIEDDATE<=@endDate))
);
GO
