create Function [dbo].[FN_TS_MasterData_GetItemPrice_XXX](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT PRC.LOGICALREF AS PriceId, UNIT.LOGICALREF AS UnitId,  PRC.CARDREF AS ItemId, PRC.PRICE AS Price, PRC.ACTIVE AS Status, PRC.PRIORITY AS Priority,
UNITSEL.CODE AS UnitCode, dbo.FN_TS_AddTime(PRC.BEGDATE, PRC.BEGTIME) As BeginDate, dbo.FN_TS_AddTime(PRC.ENDDATE, PRC.ENDTIME) As EndDate, 
PRC.CURRENCY AS CurrencyType, (CASE WHEN PRC.PTYPE=2 THEN  '11111000000'  ELSE '00000000XXX' END) AS OperationMask, '11000000' AS SaleChannelMask,
-1 AS DivisionNrs, PRC.INCVAT AS IsVatIncluded, PRC.UNITCONVERT As IsConvertible, 
PRC.CAPIBLOCK_CREADEDDATE AS CreatedDate, PRC.CAPIBLOCK_MODIFIEDDATE AS ModifiedDate
FROM LG_XXX_PRCLIST PRC WITH (NOLOCK)
INNER JOIN LG_XXX_UNITSETL UNITSEL WITH (NOLOCK) ON (PRC.UOMREF = UNITSEL.LOGICALREF)
INNER JOIN LG_XXX_ITMUNITA UNIT WITH (NOLOCK) ON (UNIT.UNITLINEREF= UNITSEL.LOGICALREF AND UNIT.ITEMREF=PRC.CARDREF)
WHERE PRC.CARDREF IN (SELECT ItemId FROM FN_TS_MasterData_GetAllItem_XXX())
AND ((PRC.CAPIBLOCK_CREADEDDATE >=@beginDate AND PRC.CAPIBLOCK_CREADEDDATE <=@endDate ) OR (PRC.CAPIBLOCK_MODIFIEDDATE>=@beginDate AND PRC.CAPIBLOCK_MODIFIEDDATE<=@endDate))
AND ((PRC.PTYPE =2 AND PRC.GRPCODE='STD') OR PRC.PTYPE=1)
);
GO
