create Function [dbo].[FN_TS_MasterData_GetClientRoute_XXX]()
RETURNS TABLE
AS RETURN
(
SELECT DISTINCT CLCARD.LOGICALREF AS ClientId, REL.SALESMANREF AS SalesmanId, CLCARD.ORDDAY AS OrdDay
FROM LG_XXX_CLCARD CLCARD WITH (NOLOCK)
INNER JOIN LG_XXX_SLSCLREL REL WITH (NOLOCK) ON CLCARD.LOGICALREF=REL.CLIENTREF  
WHERE CLCARD.ACTIVE=0 AND CLCARD.LOGICALREF IN (SELECT ClientId FROM FN_TS_MasterData_GetAllClient_XXX())
);
GO
