create Function [dbo].[FN_TS_MasterData_GetInvoice_XXX_YY](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT INVOICE.LOGICALREF AS InvoiceId, LINE.ORDFICHEREF AS OrderId, 
INVOICE.FICHENO AS InvoiceNo, INVOICE.CLIENTREF AS ClientId, INVOICE.SALESMANREF AS SalesmanId,
(CASE WHEN INVOICE.TRCODE IN (2,3) THEN 2 WHEN INVOICE.TRCODE IN (7,8) THEN 4 END) AS InvoiceType,
INVOICE.DATE_ AS InvoiceDate, INVOICE.STATUS AS InvoiceStatus,
INVOICE.SOURCEINDEX AS WarehouseNr, INVOICE.BRANCH AS Division, INVOICE.DEPARTMENT As Department, INVOICE.FACTORYNR AS Factory, 
DOCTRACKINGNR AS DockTrackingNo, INVOICE.SPECODE AS Specode,  GENEXP2 AS Specode2, GENEXP3 AS Specode3, GENEXP4 AS Specode4, GENEXP4 AS Specode5, GENEXP1 AS Note,
INVOICE.PAYDEFREF AS PaymentPlanId,  0 AS GPSLongitude, 0 AS GPSLatitude, INVOICE.CANCELLED AS IsCancelled,
INVOICE.CAPIBLOCK_CREADEDDATE AS CreatedDate, INVOICE.CAPIBLOCK_MODIFIEDDATE AS ModifiedDate,
LINE.LOGICALREF AS LineId, (CASE WHEN LINE.LINETYPE IN (0,6) THEN 0 WHEN LINE.LINETYPE=1 THEN 1 WHEN LINE.LINETYPE=2 THEN 2 END) AS LineType,
LINE.STOCKREF AS ItemId, UNITLINE.CODE AS ItemUnitCode, LINE.AMOUNT AS Quantity, 
(CASE WHEN LINE.VATINC=0 THEN  ROUND(LINE.PRICE+LINE.PRICE*LINE.VAT/100,4) ELSE LINE.PRICE END )AS Price, 

(CASE WHEN LINE.LINETYPE=2 THEN LINE.LINENET ELSE 
(SELECT ISNULL(SUM(LINENET),0) FROM  LG_XXX_YY_STLINE DISCOUNTLINE WITH (NOLOCK) WHERE DISCOUNTLINE.INVOICEREF=LINE.INVOICEREF AND DISCOUNTLINE.LINETYPE = 2 AND DISCOUNTLINE.GLOBTRANS=0 AND DISCOUNTLINE.PARENTLNREF=LINE.LOGICALREF)  END) AS DiscountAmount,
LINE.VAT As VatRate
--(CASE WHEN LINE.LINETYPE IN (1,2) THEN  LINE.DISCPER ELSE ISNULL(DISCOUNTLINE.DISCPER ,0) END) AS DiscountPercent,                                             
--ISNULL(CASE WHEN LINE.LINETYPE IN (1,2) THEN LINE.LINENET ELSE DISCOUNTLINE.LINENET END,0) AS DiscountAmount,
--ISNULL(CASE WHEN LINE.LINETYPE IN (1) THEN LINE.LINENET-LINE.LINENET*LINE.DISCPER/100  WHEN LINE.LINETYPE IN (0,6) THEN LINE.LINENET-ISNULL(DISCOUNTLINE.LINENET ,0) END,0) AS NetTotal,
--LINE.VATAMNT AS VatAmount,  
--INVOICE.TOTALDISCOUNTS AS TotalDiscounts

FROM LG_XXX_YY_STLINE LINE WITH (NOLOCK) 
LEFT JOIN LG_XXX_UNITSETL UNITLINE WITH (NOLOCK) ON UNITLINE.LOGICALREF=LINE.UOMREF
--LEFT JOIN LG_XXX_YY_STLINE DISCOUNTLINE WITH (NOLOCK) ON (DISCOUNTLINE.INVOICEREF=LINE.INVOICEREF AND DISCOUNTLINE.LINETYPE = 2 AND DISCOUNTLINE.GLOBTRANS=0 AND LINE.LOGICALREF=DISCOUNTLINE.PARENTLNREF)
INNER JOIN LG_XXX_YY_INVOICE INVOICE WITH (NOLOCK) ON INVOICE.LOGICALREF = LINE.INVOICEREF
WHERE (LINE.LINETYPE in (0,1,6) OR (LINE.LINETYPE=2 AND LINE.GLOBTRANS=1)) AND INVOICE.TRCODE IN (2,3,7,8)
AND ((INVOICE.CAPIBLOCK_CREADEDDATE >=@beginDate AND INVOICE.CAPIBLOCK_CREADEDDATE <=@endDate) OR (INVOICE.CAPIBLOCK_MODIFIEDDATE>=@beginDate AND INVOICE.CAPIBLOCK_MODIFIEDDATE<=@endDate)) 
);
GO
