CREATE Function [dbo].[FN_TS_MasterData_ClientGroupInfo_XXX]()
RETURNS TABLE
AS RETURN
(
SELECT distinct XXX AS Firm, 5 AS GroupType, SPE5.LOGICALREF AS GroupId, SPE5.DEFINITION_ As Name, SPE5.SPECODE As Code
FROM LG_XXX_CLCARD CLCARD WITH (NOLOCK)
INNER JOIN LG_XXX_SPECODES SPE5 WITH (NOLOCK) ON SPE5.SPECODE=CLCARD.SPECODE5 and SPE5.SPECODETYPE=1 and SPE5.CODETYPE=1 and SPE5.SPECODETYPE=26
WHERE CLCARD.ACTIVE=0 AND CLCARD.SPECODE5!=''

);
GO
