create   function [dbo].[FN_TS_Delivery_GetInvoiceLine_XXX_YY](@erpId int)
RETURNS TABLE
AS RETURN
(
SELECT LINE.LOGICALREF As InvoiceLineId,(CASE WHEN LINE.LINETYPE IN (0,6) THEN 0 WHEN LINE.LINETYPE=1 THEN 1 WHEN LINE.LINETYPE=2 THEN 2 END) AS LineType,
LINE.STOCKREF AS ItemId, UNITLINE.LOGICALREF AS ItemUnitId, UNITLINE.CODE AS ItemUnitCode,
LINE.AMOUNT AS Quantity, LINE.PRICE AS Price, 
(CASE WHEN LINE.LINETYPE IN (1,2) THEN  LINE.DISCPER ELSE ISNULL(DISCOUNTLINE.DISCPER ,0) END) AS DiscountPercent,                                             
ISNULL(CASE WHEN LINE.LINETYPE IN (1,2) THEN LINE.LINENET ELSE DISCOUNTLINE.LINENET END,0) AS DiscountAmount,
ISNULL(CASE WHEN LINE.LINETYPE IN (1) THEN LINE.LINENET-LINE.LINENET*LINE.DISCPER/100  WHEN LINE.LINETYPE IN (0,6) THEN LINE.LINENET-ISNULL(DISCOUNTLINE.LINENET ,0) END,0) AS NetTotal,
LINE.VATAMNT AS VatAmount, LINE.VATINC AS IsVatIncluded
FROM LG_XXX_YY_STLINE LINE WITH (NOLOCK) 
LEFT JOIN LG_XXX_UNITSETL UNITLINE WITH (NOLOCK) ON UNITLINE.LOGICALREF=LINE.UOMREF
LEFT JOIN LG_XXX_YY_STLINE DISCOUNTLINE WITH (NOLOCK) ON (DISCOUNTLINE.STFICHEREF=LINE.STFICHEREF AND DISCOUNTLINE.LINETYPE = 2 AND DISCOUNTLINE.GLOBTRANS=0 AND LINE.LOGICALREF=DISCOUNTLINE.PARENTLNREF)
WHERE LINE.INVOICEREF= @erpId AND LINE.LINETYPE in (0,1,6)
);
GO
