create   function [dbo].[FN_TS_Report_GetClientBalance_XXX_YY](@clientId int, @date datetime)
RETURNS TABLE
AS RETURN
(
SELECT ISNULL(SUM((CASE WHEN CLFLINE.SIGN=0 THEN 1 ELSE -1 END)*CLFLINE.AMOUNT),0) As Balance
FROM LG_XXX_YY_CLFLINE CLFLINE WITH (NOLOCK) 
WHERE CLFLINE.DATE_ < @date AND CLFLINE.CLIENTREF = @clientId AND CLFLINE.CANCELLED=0
);
GO
