create   function [dbo].[FN_TS_MasterData_GetFactForSalesman_XXX_YY](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
SELECT STLINE.SALESMANREF AS SalesmanId, STLINE.STOCKREF AS ItemId,
ITMUNITA.LOGICALREF AS ItemUnitId, ROUND( SUM (( CASE WHEN STLINE.TRCODE IN (7,8) THEN 1 ELSE -1 END ) *STLINE.AMOUNT* (CASE WHEN STLINE.UINFO2=0 THEN 1 ELSE STLINE.UINFO2 END)/(CASE WHEN STLINE.UINFO1=0 THEN 1 ELSE STLINE.UINFO1 END) ),2) AS  Quantity ,
ROUND( SUM (( CASE WHEN STLINE.TRCODE IN (7,8) THEN 1 ELSE -1 END ) * ISNULL(CASE WHEN STLINE.LINETYPE IN (1) THEN STLINE.LINENET-STLINE.LINENET*STLINE.DISCPER/100  WHEN STLINE.LINETYPE=0 THEN STLINE.LINENET END,0)),2) AS  Amount ,
STLINE.DATE_ AS Date
FROM  LG_XXX_YY_STLINE STLINE WITH (NOLOCK)
INNER JOIN LG_XXX_ITMUNITA ITMUNITA WITH (NOLOCK) ON ITMUNITA.ITEMREF=STLINE.STOCKREF AND ITMUNITA.LINENR=1
WHERE STLINE.TRCODE IN (7,8) AND STLINE.STATUS=0 AND STLINE.CANCELLED=0 AND STLINE.SALESMANREF>0 AND STLINE.LINETYPE IN (0,1,6)
AND STLINE.DATE_>=@beginDate AND STLINE.DATE_<@endDate 
GROUP BY STLINE.DATE_, STLINE.SALESMANREF, STLINE.STOCKREF, ITMUNITA.LOGICALREF
);
GO
