create   function [dbo].[FN_TS_Report_GetClientTopSoldItem_XXX_YY](@beginDate datetime, @endDate datetime, @clientId int)
RETURNS TABLE
AS RETURN
(
WITH ActionLines AS (
SELECT STLINE.STOCKREF, SUM((CASE WHEN STLINE.TRCODE IN (2,3) THEN -1 ELSE 1 END)*VATMATRAH) AS Amount, 
SUM((CASE WHEN STLINE.TRCODE IN (2,3) THEN -1 ELSE 1 END)*STLINE.AMOUNT*((CASE WHEN STLINE.UINFO2=0 THEN 1 ELSE STLINE.UINFO2 END)/(CASE WHEN STLINE.UINFO1=0 THEN 1 ELSE STLINE.UINFO1 END)))  AS Quantity
FROM LG_XXX_YY_STLINE STLINE WITH(NOLOCK)
WHERE STLINE.CANCELLED=0 AND STLINE.DATE_ Between @beginDate AND @endDate AND STLINE.CLIENTREF=@clientId AND TRCODE IN (2,3,7,8) AND LINETYPE IN (0,1,6)
GROUP BY STLINE.STOCKREF)

SELECT ITEM.NAME AS ItemName, ITEM.CODE AS ItemCode, ISNULL(ActionLines.Amount,0) AS Amount, 
ISNULL(ActionLines.Quantity,0) AS Quantity, UNITSEL.NAME AS UnitName, 'AZN' AS Currency
FROM ActionLines
INNER JOIN LG_XXX_ITEMS ITEM WITH (NOLOCK) ON ITEM.LOGICALREF=ActionLines.STOCKREF
INNER JOIN LG_XXX_ITMUNITA UNITA WITH (NOLOCK) ON UNITA.ITEMREF=ActionLines.STOCKREF
INNER JOIN LG_XXX_UNITSETL UNITSEL WITH (NOLOCK) ON (UNITSEL.LOGICALREF= UNITA.UNITLINEREF AND UNITSEL.MAINUNIT=1)
);
GO
