CREATE Function [dbo].[FN_TS_Report_GetSalesmanDebt_XXX_YY]()
RETURNS TABLE
AS RETURN
(
Select SLSCLREL.SALESMANREF As SalesmanId,  CLCARD.LOGICALREF As ClientId, CLCARD.CODE As ClientCode, CLCARD.DEFINITION_ As ClientName, 
PCARD.EDINO As Edino, GNTOTCL.DEBIT As Debit, GNTOTCL.CREDIT As Credit, CLCARD.CITY AS City, CLCARD.SPECODE AS Specode, 162 As CurrencyType, 'AZN' As CurrencyCode, 1 AS OrderNo
FROM LG_XXX_YY_GNTOTCL GNTOTCL WITH (NOLOCK)
Inner Join LG_XXX_CLCARD CLCARD WITH (NOLOCK) ON GNTOTCL.CARDREF = CLCARD.LOGICALREF
Left Join LG_XXX_CLCARD PCARD WITH (NOLOCK) ON CLCARD.PARENTCLREF = PCARD.LOGICALREF
Inner Join LG_XXX_SLSCLREL SLSCLREL WITH (NOLOCK) ON (SLSCLREL.CLIENTREF = GNTOTCL.CARDREF) 
Where GNTOTCL.TOTTYP = 1 
);
GO
