CREATE VIEW [dbo].[VW_TS_Report_OrderStatus_XXX_YY]
AS 
(
Select ORFICHE.LOGICALREF AS OrficheRef,
ORFICHE.FICHENO AS FicheNo, 
ORFICHE.DATE_ AS Date, 
ORFICHE.NETTOTAL AS NetTotal,
SLSMAN.LOGICALREF AS SalesManRef,
SLSMAN.DEFINITION_ AS SalesManName,
SLSMAN.CODE AS SalesManCode,
Case ORFICHE.STATUS WHEN 4 Then 1 WHEN 2 THEN 0 WHEN 1 THEN 2 End AS OrderStatus,
CARD.CODE AS ClientCode,
CARD.SPECODE4 AS ClientSpecode4,
ORFICHE.CLIENTREF AS ClientRef,
CARD.DEFINITION_ AS ClientName,
ORFICHE.STATUS AS Status 
From LG_XXX_YY_ORFICHE ORFICHE With (NoLock)
Inner Join LG_XXX_CLCARD CARD With (NoLock) On CARD.LOGICALREF = ORFICHE.CLIENTREF
INNER JOIN LG_SLSMAN SLSMAN ON SLSMAN.LOGICALREF = ORFICHE.SALESMANREF
Where ORFICHE.STATUS IN (1,2,4) 
)
GO
