CREATE VIEW [dbo].[VW_TS_GetCashInfo_XXX_YY]
AS 
SELECT LOGICALREF AS FicheRef, FICHENO AS FicheNo, AMOUNT AS Amount, STATUS AS Status, TRANGRPNO As TranGroupNo
FROM LG_XXX_YY_KSLINES WITH (NOLOCK) 
GO
