CREATE VIEW [dbo].[VW_TS_GetInvoiceInfo_XXX_YY]
AS 
SELECT LOGICALREF AS FicheRef, FICHENO As FicheNo, NETTOTAL As NetTotal, TOTALDISCOUNTS AS TotalDiscount, TOTALDISCOUNTS-TOTALPROMOTIONS AS DiscountAmount, 
STATUS AS Status, TOTALVAT AS TotalVat, GROSSTOTAL AS GrossTotal 
FROM LG_XXX_YY_INVOICE WITH (NOLOCK)
GO
