create Function [dbo].[FN_TS_MasterData_GetItemSerialNumber_XXX_YY](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
select distinct top 100 XXX AS Firm, ITEMS.LOGICALREF AS ItemId, SOURCEINDEX AS WarehouseNr, '' AS SerialNumber  from LG_XXX_ITEMS ITEMS
join LG_XXX_YY_SLTRANS SLTRANS ON ITEMS.LOGICALREF = SLTRANS.ITEMREF
join LG_XXX_YY_SERILOTN SERILOTN ON SERILOTN.ITEMREF = ITEMS.LOGICALREF
JOIN LG_XXX_YY_STLINE STLINE ON STLINE.LOGICALREF = SLTRANS.SLREF
where 
TRACKTYPE = 2 
);
