CREATE  Function [dbo].[FN_TS_Report_GetWarehouseTransferLineData_XXX_YY](@ficheId int)
RETURNS TABLE
AS RETURN
(
SELECT ITEM.[NAME] ItemName,ITEM.CODE ItemCode, (CASE WHEN STLINE.STATUS=0 THEN STLINE.AMOUNT ELSE 0 END) AcceptedQuantity,
STLINE.DATE_ [Date], UNITSETL.CODE ItemUnitCode
FROM LG_XXX_YY_STLINE STLINE
INNER JOIN LG_XXX_ITEMS ITEM ON ITEM.LOGICALREF = STLINE.STOCKREF
INNER JOIN LG_XXX_UNITSETL UNITSETL ON UNITSETL.LOGICALREF = STLINE.UOMREF
WHERE STLINE.IOCODE = 3 AND  STLINE.STFICHEREF = @ficheId
)