-- Cədvəl: WPM_UserTask
CREATE NONCLUSTERED INDEX [IX_WPM_UserTask_TaskId] ON [dbo].[WPM_UserTask]
(
	[TaskId] ASC,
	[UserId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
      DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
-- Cədvəl: WPM_TaskClient

CREATE NONCLUSTERED INDEX [IX_WPM_TaskClient_TaskId_ClientId] ON [dbo].[WPM_TaskClient]
(
	[TaskId] ASC,
	[ClientId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
      DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
-- Cədvəl: WPM_PhotoTaskMapping

CREATE NONCLUSTERED INDEX [IX_WPM_PhotoTaskMapping_TaskId] ON [dbo].[WPM_PhotoTaskMapping]
(
	[TaskId] ASC
)
INCLUDE([SourceType]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
      DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

-- Cədvəl: WPM_Attachment
CREATE NONCLUSTERED INDEX [IX_WPM_Attachment_ReferenceId_Type] ON [dbo].[WPM_Attachment]
(
	[ReferenceId] ASC,
	[Type] ASC
)
INCLUDE([SecureUrl]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
      DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

-- Cədvəl: WPM_TaskTicketAction
CREATE NONCLUSTERED INDEX [IX_WPM_TaskTicketAction_TaskTicketId] ON [dbo].[WPM_TaskTicketAction]
(
	[TaskTicketId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
      DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

-- Cədvəl: WPM_TaskTicket
CREATE NONCLUSTERED INDEX [IX_WPM_TaskTicket_TaskId_ClientId_UserId] ON [dbo].[WPM_TaskTicket]
(
	[TaskId] ASC,
	[ClientId] ASC,
	[UserId] ASC
)
INCLUDE([CreatedDate],[FinalizedDate]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
      DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
-- Cədvəl: WPM_TaskSchedule

CREATE NONCLUSTERED INDEX [IX_WPM_TaskSchedule_TaskId] ON [dbo].[WPM_TaskSchedule]
(
	[TaskId] ASC
)
INCLUDE([StartDate],[EndDate]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
      DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

-- Cədvəl: WPM_Task
CREATE NONCLUSTERED INDEX [IX_WPM_Task_Firm_IsDeleted_Id] ON [dbo].[WPM_Task]
(
	[Firm] ASC,
	[IsDeleted] ASC,
	[Id] ASC
)
INCLUDE([Name],[CreatedDate],[CreatedUserId],[CategoryReason],[SubcategoryReason],[GroupReason]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
      DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

