CREATE Function [dbo].[FN_TS_Integration_GetWarehouseOperation_XXX_YY](@recordId int)
RETURNS TABLE
AS RETURN
(
SELECT  COMPBRANCH AS DivisionIn, BRANCH AS DivisionOut, DESTINDEX AS WarehouseIn, SOURCEINDEX AS WarehouseOut, FACTORYNR AS FactoryNr, STATUS AS [Status] , FICHENO As FicheNo
from LG_XXX_YY_STFICHE WITH (NOLOCK)
WHERE LOGICALREF=@recordId
);

go

CREATE Function [dbo].[FN_TS_Integration_GetWarehouseOperationLine_XXX_YY](@recordId int)
RETURNS TABLE
AS RETURN
(
SELECT LINE.STOCKREF AS ItemId, LINE.AMOUNT AS Quantity, UNITLINE.CODE AS ItemUnitCode
FROM LG_XXX_YY_STLINE  LINE WITH (NOLOCK) 
LEFT JOIN LG_XXX_UNITSETL UNITLINE WITH (NOLOCK)  ON UNITLINE.LOGICALREF=LINE.UOMREF
WHERE STFICHEREF =@recordId AND ( (TRCODE = 25 AND IOCODE=2) OR TRCODE IN (12,13))
);


