
ALTER TABLE WPM_Task 
ADD ScanAtStart bit NOT NULL 
CONSTRAINT WPM_Task_ScanAtStart DEFAULT 0
WITH VALUES

GO

ALTER TABLE WPM_Task 
ADD ScanAtStop bit NOT NULL 
CONSTRAINT WPM_Task_ScanAtStop DEFAULT 0
WITH VALUES