/****** Object:  Index [IX_IsCancelled]    Script Date: 9/26/2021 2:16:53 PM ******/
CREATE NONCLUSTERED INDEX [IX_IsCancelled] ON [dbo].[ERP_Invoice]
(
	[IsCancelled] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_IsDeleted]    Script Date: 9/26/2021 2:20:09 PM ******/
CREATE NONCLUSTERED INDEX [IX_IsDeleted] ON [dbo].[ERP_Invoice]
(
	[IsDeleted] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
