-- view which is being used by function was generated by Avrora
create Function [dbo].[FN_TS_MasterData_GetWarehouseClientGroupRestiction]()
RETURNS TABLE
AS RETURN
(
SELECT FIRMNR as Firm, NR as WarehouseNr, SITEID as GroupId  FROM L_CAPIWHOUSE WHERE SITEID>0
);