-- view which is being used by function was generated by Avrora
create Function [dbo].[FN_TS_MasterData_GetClientGroupForItemCatalog_XXX](@beginDate datetime, @endDate datetime)
RETURNS TABLE
AS RETURN
(
select Firm, ClientId, ClientGroupId AS GroupId, CreatedDate, ModifiedDate from V_TayqaSale_ClientCatalogGroup
)