
ALTER TABLE WPM_Tag ADD Color NVARCHAR(10) NULL;
GO
UPDATE WPM_Tag SET Color = '#4B9CE7';
GO
ALTER TABLE WPM_Tag ALTER COLUMN Color NVARCHAR(10) NOT NULL;
GO
ALTER TABLE WPM_TaskTag ADD Color NVARCHAR(10) NULL;
GO
UPDATE WPM_TaskTag SET Color = '#4B9CE7';
GO
ALTER TABLE WPM_TaskTag ALTER COLUMN Color NVARCHAR(10) NOT NULL;
GO
