CREATE Function dbo.FN_TS_Report_GetOperationLine_XXX_YY(@operationId int , @docType tinyint)
RETURNS TABLE
AS RETURN
(
SELECT LINE.ORDFICHEREF AS OrderId, ITEM.LOGICALREF AS ItemId, ITEM.CODE AS ItemCode, ITEM.Name AS ItemName, UNITLINE.NAME AS UnitName,
LINE.LINETYPE AS LineType, LINE.AMOUNT AS Quantity, (CASE WHEN LINE.VATINC =1 THEN LINE.PRICE ELSE LINE.PRICE*(1+LINE.VAT/100)  END) AS Price, 
(CASE WHEN LINE.LINETYPE=1 THEN 0 ELSE (LINE.LINENET+LINE.VATAMNT-LINE.DISTDISC) END) AS Total,'AZN' As CurrencyCode
FROM LG_XXX_YY_ORFLINE LINE WITH (NOLOCK)
LEFT JOIN LG_XXX_ITEMS ITEM WITH (NOLOCK) ON LINE.STOCKREF = ITEM.LOGICALREF
LEFT JOIN LG_XXX_UNITSETL UNITLINE WITH (NOLOCK) ON UNITLINE.LOGICALREF=LINE.UOMREF
INNER JOIN TayqaSale..OP_GeneralLog GLog with (nolock) on GLog.TigerId = LINE.ORDFICHEREF AND ImportResult = 0
INNER JOIN TayqaSale..OP_IncomingLog ILog with (nolock) on GLog.RequestId = ILog.Id AND ILog.DocType = @docType
WHERE LINE.LINETYPE in (0,1,6) AND LINE.ORDFICHEREF=@operationId
);